export enum ActionTypes {
    ADD_ACCOUNT_ITEM = 'ADD_ACCOUNT_ITEM',
    EDIT_ACCOUNT_ITEM = 'EDIT_ACCOUNT_ITEM',
    DELETE_ACCOUNT_ITEM = 'DELETE_ACCOUNT_ITEM',  
    MOVE_ACCOUNT_ITEM = 'MOVE_ACCOUNT_ITEM',
}